version: '3.8'

services:
  gateway:
    build: .
    ports:
      - "8080:8080"
    networks:
      - app-network


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - gateway

networks:
  app-network: