spring:
  application:
    name: 3runner-gateway
  config:
    activate:
      on-profile: prod
  cloud:
    gateway:
      routes:
        - id: auth
          uri:
            lb://3RUNNER-AUTH
          predicates:
            - Path=/auth/**

        - id: bookstore-image
          uri: lb://3RUNNER-BOOKSTORE
          predicates:
            - Path=/bookstore/images/**

        - id: bookstore
          uri: lb://3RUNNER-BOOKSTORE
          predicates:
            - Path=/bookstore/**
          filters:
            - AuthorizationFilter

        - id: coupon
          uri: lb://3RUNNER-COUPON
          predicates:
            - Path=/coupon/**

  data:
    redis:
      host: 133.186.241.167
      port: 6379
      database: 15
      password: "*N2vya7H@muDTwdNMR!"
  jwt:
    secret: aaaasqwlkljlfasdfqwerafcxvzpojijoijopjewndllllllsserrrrrrwqexc


logging:
  level:
    root: debug

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone:
        http://admin:1234@eureka:8761/eureka
  instance:
    prefer-ip-address: true
