spring:
  config:
    activate:
      on-profile: prod

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone:
        http://admin:1234@133.186.143.40:8761/eureka,http://admin:1234@133.186.143.40:8762/eureka
  instance:
    prefer-ip-address: true


