server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: 3runner-gateway
  profiles:
    default: dev
  cloud:
    gateway:
      routes:
        - id: auth
          uri:
            lb://3RUNNER-AUTH
          predicates:
            - Path=/auth/**

        - id: bookstore-image
          uri: lb://3RUNNER-BOOKSTORE
          predicates:
            - Path=/bookstore/images/**

        - id: bookstore
          uri: lb://3RUNNER-BOOKSTORE
          predicates:
            - Path=/bookstore/**
          filters:
            - AuthorizationFilter
          metadata:
            cors:
              allowedOrigins: 'http://3runner.shop'
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTION
              allowedHeaders: '*'
              maxAge: 30

        - id: coupon
          uri: lb://3RUNNER-COUPON
          predicates:
            - Path=/coupon/**
  jwt:
    secret: aaaasqwlkljlfasdfqwerafcxvzpojijoijopjewndllllllsserrrrrrwqexc

  data:
    redis:
      host: 133.186.241.167
      port: 6379
      database: 15
      password: "*N2vya7H@muDTwdNMR!"

logging:
  level:
    root: debug




