server:
  port: 8080

spring:
  application:
    name: 3runner-gateway
  profiles:
    default: prod
  jwt:
    secret: aaaasqwlkljlfasdfqwerafcxvzpojijoijopjewndllllllsserrrrrrwqexc

  data:
    redis:
      host: 133.186.241.167
      port: 6379
      database: 15
      password: "*N2vya7H@muDTwdNMR!"

logging:
  level:
    root: debug




