server:
  port: 8080

spring:
  application:
    name: 3runner-gateway
  profiles:
    default: prod
  cloud:
    gateway:
      routes:
        - id: auth
          uri:
            lb://3RUNNER-AUTH
          predicates:
            - Path=/auth/**

        - id: bookstore-image
          uri: lb://3RUNNER-BOOKSTORE
          predicates:
            - Path=/bookstore/images/**

        - id: bookstore
          uri: lb://3RUNNER-BOOKSTORE
          predicates:
            - Path=/bookstore/**
          filters:
            - AuthorizationFilter

        - id: coupon
          uri: lb://3RUNNER-COUPON
          predicates:
            - Path=/coupon/**

  data:
    redis:
      host: 133.186.241.167
      port: 6379
      database: 15
      password: "*N2vya7H@muDTwdNMR!"
  jwt:
    secret: aaaasqwlkljlfasdfqwerafcxvzpojijoijopjewndllllllsserrrrrrwqexc

logging:
  level:
    root: debug




